name: "Daily Fetch"
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fetchData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: v20.16.x
          cache: npm
      - name: Install
        run: npm install
      - name: Run My Script
        run: |
          npm run hello-world